#server setting
server:
  port: 8081
  address: localhost
  context-path: /portal
  tomcat:
    # 解析含有中文名的文件的url
    uri-encoding: utf-8
    # 最大连接数
    max-connections: 1000
    # 最大线程数，即最大并发数。
    max-threads: 500
    # 最小备用线程数
    min-spare-threads: 20
    # 线程数达到maxThreads后，后续请求会被放入一个等待队列，acceptCount是这个队列的大小
    accept-count: 100
    # tomcat连接器
    connector: org.apache.coyote.http11.Http11NioProtocol
    # tomcat优化
    optimize: true
  session:
    cookie:
#      domain:
      http-only: true
      max-age: 3600000
#  context-parameters:
    # logback配置文件服务地址
#    logback-config-location: http://172.16.225.98:8888/logback/framework/website
    # logback是否显示WebAppRoot
#    logback-expose-webapp-root: true
#spring mvc setting
spring:
#  profiles:
#    active: dev
  thymeleaf:
    cache: false
    suffix: .html
  mvc:
    # 指定静态资源处理路径
    static-path-pattern: /static/**
    view:
      suffix: .html
  application:
    name: dubbox-test-website
  http:
    multipart:
      enabled: true
      max-file-size: 8MB
      max-request-size: 20MB
cache:
  redis:
#    host: 172.16.225.98:
    host: 172.16.228.43
    port: 6379
    password: redis123
    pool:
      max-wait: 10000
      max-idle: 100
      min-idle: 50
      max-active: 300
#dubbo setting
dubbo:
  application:
    #服务消费名称信息
    name: dubbo_consumer
    #日志适配
    logger: slf4j
  registry:
    protocol: zookeeper
    #zookeeper注册中心服务地址
    address: 172.16.229.205:2181,172.16.229.205:2182,172.16.229.205:2183
    #注册中心不存在时，是否报错
    check: false
    #是否向此注册中心注册服务，如果设为false，将只订阅，不注册
    register: true
    #是否向此注册中心订阅服务，如果设为false，将只注册，不订阅
    subscribe: true
    #注册中心请求超时时间(毫秒)
    timeout: 2000
  rpc:
    service-package: com.sfsctech.website.thymeleaf.rpc
#common setting
website:
  support:
    # 静态资源服务
    static-resources: http://localhost:8080
    # 首页路径
    welcome-file: /index
  session:
    # session认证模式
#    authentication: sso
    # session过滤排除路径
    exclude-path: /index, /login
  security:
#    cors:
#      enabled: true
#      cross-domain:
#        - url: http://www.zzl.com
#          access-control-allow-methods: GET
    csrf:
      # csrf拦截排除路径
#     intercept-exclude-path: /**
      # csrf验证排除路径
      verify-exclude-path: /index
#    ddos:
#      enabled: true
#      time-span: 60
#      limit: 1
#      whitelist:
#        - ip: 127.0.0.1
#          time-span: -1
#          limit: 10
logging:
  path: D:\opt\logs
  config: classpath:logback-custom.xml