package com.sfsctech.framework.mapper;

import com.sfsctech.framework.model.domain.TSysAccount;
import com.sfsctech.framework.model.domain.TSysAccountExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TSysAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    long countByExample(TSysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    int deleteByExample(TSysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    int insert(TSysAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    int insertSelective(TSysAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    List<TSysAccount> selectByExample(TSysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    TSysAccount selectByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TSysAccount record, @Param("example") TSysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TSysAccount record, @Param("example") TSysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSysAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysAccount record);
}