package com.test.data.repository.model.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TExamPaperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public TExamPaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("Guid is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("Guid is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("Guid =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("Guid <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("Guid >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("Guid >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("Guid <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("Guid <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("Guid like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("Guid not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("Guid in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("Guid not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("Guid between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("Guid not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeIsNull() {
            addCriterion("GuidExamNotice is null");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeIsNotNull() {
            addCriterion("GuidExamNotice is not null");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeEqualTo(String value) {
            addCriterion("GuidExamNotice =", value, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeNotEqualTo(String value) {
            addCriterion("GuidExamNotice <>", value, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeGreaterThan(String value) {
            addCriterion("GuidExamNotice >", value, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeGreaterThanOrEqualTo(String value) {
            addCriterion("GuidExamNotice >=", value, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeLessThan(String value) {
            addCriterion("GuidExamNotice <", value, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeLessThanOrEqualTo(String value) {
            addCriterion("GuidExamNotice <=", value, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeLike(String value) {
            addCriterion("GuidExamNotice like", value, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeNotLike(String value) {
            addCriterion("GuidExamNotice not like", value, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeIn(List<String> values) {
            addCriterion("GuidExamNotice in", values, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeNotIn(List<String> values) {
            addCriterion("GuidExamNotice not in", values, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeBetween(String value1, String value2) {
            addCriterion("GuidExamNotice between", value1, value2, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andGuidexamnoticeNotBetween(String value1, String value2) {
            addCriterion("GuidExamNotice not between", value1, value2, "guidexamnotice");
            return (Criteria) this;
        }

        public Criteria andPapernameIsNull() {
            addCriterion("PaperName is null");
            return (Criteria) this;
        }

        public Criteria andPapernameIsNotNull() {
            addCriterion("PaperName is not null");
            return (Criteria) this;
        }

        public Criteria andPapernameEqualTo(String value) {
            addCriterion("PaperName =", value, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameNotEqualTo(String value) {
            addCriterion("PaperName <>", value, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameGreaterThan(String value) {
            addCriterion("PaperName >", value, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameGreaterThanOrEqualTo(String value) {
            addCriterion("PaperName >=", value, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameLessThan(String value) {
            addCriterion("PaperName <", value, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameLessThanOrEqualTo(String value) {
            addCriterion("PaperName <=", value, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameLike(String value) {
            addCriterion("PaperName like", value, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameNotLike(String value) {
            addCriterion("PaperName not like", value, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameIn(List<String> values) {
            addCriterion("PaperName in", values, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameNotIn(List<String> values) {
            addCriterion("PaperName not in", values, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameBetween(String value1, String value2) {
            addCriterion("PaperName between", value1, value2, "papername");
            return (Criteria) this;
        }

        public Criteria andPapernameNotBetween(String value1, String value2) {
            addCriterion("PaperName not between", value1, value2, "papername");
            return (Criteria) this;
        }

        public Criteria andPapertypeIsNull() {
            addCriterion("PaperType is null");
            return (Criteria) this;
        }

        public Criteria andPapertypeIsNotNull() {
            addCriterion("PaperType is not null");
            return (Criteria) this;
        }

        public Criteria andPapertypeEqualTo(Integer value) {
            addCriterion("PaperType =", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeNotEqualTo(Integer value) {
            addCriterion("PaperType <>", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeGreaterThan(Integer value) {
            addCriterion("PaperType >", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PaperType >=", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeLessThan(Integer value) {
            addCriterion("PaperType <", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeLessThanOrEqualTo(Integer value) {
            addCriterion("PaperType <=", value, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeIn(List<Integer> values) {
            addCriterion("PaperType in", values, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeNotIn(List<Integer> values) {
            addCriterion("PaperType not in", values, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeBetween(Integer value1, Integer value2) {
            addCriterion("PaperType between", value1, value2, "papertype");
            return (Criteria) this;
        }

        public Criteria andPapertypeNotBetween(Integer value1, Integer value2) {
            addCriterion("PaperType not between", value1, value2, "papertype");
            return (Criteria) this;
        }

        public Criteria andRatioIsNull() {
            addCriterion("Ratio is null");
            return (Criteria) this;
        }

        public Criteria andRatioIsNotNull() {
            addCriterion("Ratio is not null");
            return (Criteria) this;
        }

        public Criteria andRatioEqualTo(String value) {
            addCriterion("Ratio =", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioNotEqualTo(String value) {
            addCriterion("Ratio <>", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioGreaterThan(String value) {
            addCriterion("Ratio >", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioGreaterThanOrEqualTo(String value) {
            addCriterion("Ratio >=", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioLessThan(String value) {
            addCriterion("Ratio <", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioLessThanOrEqualTo(String value) {
            addCriterion("Ratio <=", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioLike(String value) {
            addCriterion("Ratio like", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioNotLike(String value) {
            addCriterion("Ratio not like", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioIn(List<String> values) {
            addCriterion("Ratio in", values, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioNotIn(List<String> values) {
            addCriterion("Ratio not in", values, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioBetween(String value1, String value2) {
            addCriterion("Ratio between", value1, value2, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioNotBetween(String value1, String value2) {
            addCriterion("Ratio not between", value1, value2, "ratio");
            return (Criteria) this;
        }

        public Criteria andExamdateIsNull() {
            addCriterion("ExamDate is null");
            return (Criteria) this;
        }

        public Criteria andExamdateIsNotNull() {
            addCriterion("ExamDate is not null");
            return (Criteria) this;
        }

        public Criteria andExamdateEqualTo(Date value) {
            addCriterion("ExamDate =", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateNotEqualTo(Date value) {
            addCriterion("ExamDate <>", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateGreaterThan(Date value) {
            addCriterion("ExamDate >", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateGreaterThanOrEqualTo(Date value) {
            addCriterion("ExamDate >=", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateLessThan(Date value) {
            addCriterion("ExamDate <", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateLessThanOrEqualTo(Date value) {
            addCriterion("ExamDate <=", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateIn(List<Date> values) {
            addCriterion("ExamDate in", values, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateNotIn(List<Date> values) {
            addCriterion("ExamDate not in", values, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateBetween(Date value1, Date value2) {
            addCriterion("ExamDate between", value1, value2, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateNotBetween(Date value1, Date value2) {
            addCriterion("ExamDate not between", value1, value2, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamtimeIsNull() {
            addCriterion("ExamTime is null");
            return (Criteria) this;
        }

        public Criteria andExamtimeIsNotNull() {
            addCriterion("ExamTime is not null");
            return (Criteria) this;
        }

        public Criteria andExamtimeEqualTo(Integer value) {
            addCriterion("ExamTime =", value, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeNotEqualTo(Integer value) {
            addCriterion("ExamTime <>", value, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeGreaterThan(Integer value) {
            addCriterion("ExamTime >", value, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ExamTime >=", value, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeLessThan(Integer value) {
            addCriterion("ExamTime <", value, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeLessThanOrEqualTo(Integer value) {
            addCriterion("ExamTime <=", value, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeIn(List<Integer> values) {
            addCriterion("ExamTime in", values, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeNotIn(List<Integer> values) {
            addCriterion("ExamTime not in", values, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeBetween(Integer value1, Integer value2) {
            addCriterion("ExamTime between", value1, value2, "examtime");
            return (Criteria) this;
        }

        public Criteria andExamtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ExamTime not between", value1, value2, "examtime");
            return (Criteria) this;
        }

        public Criteria andQuestionbankIsNull() {
            addCriterion("QuestionBank is null");
            return (Criteria) this;
        }

        public Criteria andQuestionbankIsNotNull() {
            addCriterion("QuestionBank is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionbankEqualTo(Integer value) {
            addCriterion("QuestionBank =", value, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankNotEqualTo(Integer value) {
            addCriterion("QuestionBank <>", value, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankGreaterThan(Integer value) {
            addCriterion("QuestionBank >", value, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankGreaterThanOrEqualTo(Integer value) {
            addCriterion("QuestionBank >=", value, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankLessThan(Integer value) {
            addCriterion("QuestionBank <", value, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankLessThanOrEqualTo(Integer value) {
            addCriterion("QuestionBank <=", value, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankIn(List<Integer> values) {
            addCriterion("QuestionBank in", values, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankNotIn(List<Integer> values) {
            addCriterion("QuestionBank not in", values, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankBetween(Integer value1, Integer value2) {
            addCriterion("QuestionBank between", value1, value2, "questionbank");
            return (Criteria) this;
        }

        public Criteria andQuestionbankNotBetween(Integer value1, Integer value2) {
            addCriterion("QuestionBank not between", value1, value2, "questionbank");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("Creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("Creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("Creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("Creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("Creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("Creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("Creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("Creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("Creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("Creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("Creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("Creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exam_paper
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}