package com.test.data.repository.model.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TPaperQuestionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public TPaperQuestionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("Guid is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("Guid is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("Guid =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("Guid <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("Guid >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("Guid >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("Guid <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("Guid <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("Guid like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("Guid not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("Guid in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("Guid not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("Guid between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("Guid not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperIsNull() {
            addCriterion("GuidExamPaper is null");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperIsNotNull() {
            addCriterion("GuidExamPaper is not null");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperEqualTo(String value) {
            addCriterion("GuidExamPaper =", value, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperNotEqualTo(String value) {
            addCriterion("GuidExamPaper <>", value, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperGreaterThan(String value) {
            addCriterion("GuidExamPaper >", value, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperGreaterThanOrEqualTo(String value) {
            addCriterion("GuidExamPaper >=", value, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperLessThan(String value) {
            addCriterion("GuidExamPaper <", value, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperLessThanOrEqualTo(String value) {
            addCriterion("GuidExamPaper <=", value, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperLike(String value) {
            addCriterion("GuidExamPaper like", value, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperNotLike(String value) {
            addCriterion("GuidExamPaper not like", value, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperIn(List<String> values) {
            addCriterion("GuidExamPaper in", values, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperNotIn(List<String> values) {
            addCriterion("GuidExamPaper not in", values, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperBetween(String value1, String value2) {
            addCriterion("GuidExamPaper between", value1, value2, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexampaperNotBetween(String value1, String value2) {
            addCriterion("GuidExamPaper not between", value1, value2, "guidexampaper");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsIsNull() {
            addCriterion("GuidExamQuestions is null");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsIsNotNull() {
            addCriterion("GuidExamQuestions is not null");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsEqualTo(String value) {
            addCriterion("GuidExamQuestions =", value, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsNotEqualTo(String value) {
            addCriterion("GuidExamQuestions <>", value, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsGreaterThan(String value) {
            addCriterion("GuidExamQuestions >", value, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsGreaterThanOrEqualTo(String value) {
            addCriterion("GuidExamQuestions >=", value, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsLessThan(String value) {
            addCriterion("GuidExamQuestions <", value, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsLessThanOrEqualTo(String value) {
            addCriterion("GuidExamQuestions <=", value, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsLike(String value) {
            addCriterion("GuidExamQuestions like", value, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsNotLike(String value) {
            addCriterion("GuidExamQuestions not like", value, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsIn(List<String> values) {
            addCriterion("GuidExamQuestions in", values, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsNotIn(List<String> values) {
            addCriterion("GuidExamQuestions not in", values, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsBetween(String value1, String value2) {
            addCriterion("GuidExamQuestions between", value1, value2, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andGuidexamquestionsNotBetween(String value1, String value2) {
            addCriterion("GuidExamQuestions not between", value1, value2, "guidexamquestions");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_paper_questions
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}