server:
  port: 10000
spring:
  application:
    name: config-server
website:
  support:
    custom-config:
      svn-uri: svn://172.16.225.98/repositories/service-config/
      svn-username: admin
      svn-password: 4880300
      svn-path: D:\logback