package com.test.data.repository.model.domain;

import java.util.Date;

public class TExamPaper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.GuidExamNotice
     *
     * @mbg.generated
     */
    private String guidexamnotice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.PaperName
     *
     * @mbg.generated
     */
    private String papername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.PaperType
     *
     * @mbg.generated
     */
    private Integer papertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.Ratio
     *
     * @mbg.generated
     */
    private String ratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.ExamDate
     *
     * @mbg.generated
     */
    private Date examdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.ExamTime
     *
     * @mbg.generated
     */
    private Integer examtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.QuestionBank
     *
     * @mbg.generated
     */
    private Integer questionbank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.Creator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.ID
     *
     * @return the value of t_exam_paper.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.ID
     *
     * @param id the value for t_exam_paper.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.Guid
     *
     * @return the value of t_exam_paper.Guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.Guid
     *
     * @param guid the value for t_exam_paper.Guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.GuidExamNotice
     *
     * @return the value of t_exam_paper.GuidExamNotice
     *
     * @mbg.generated
     */
    public String getGuidexamnotice() {
        return guidexamnotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.GuidExamNotice
     *
     * @param guidexamnotice the value for t_exam_paper.GuidExamNotice
     *
     * @mbg.generated
     */
    public void setGuidexamnotice(String guidexamnotice) {
        this.guidexamnotice = guidexamnotice == null ? null : guidexamnotice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.PaperName
     *
     * @return the value of t_exam_paper.PaperName
     *
     * @mbg.generated
     */
    public String getPapername() {
        return papername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.PaperName
     *
     * @param papername the value for t_exam_paper.PaperName
     *
     * @mbg.generated
     */
    public void setPapername(String papername) {
        this.papername = papername == null ? null : papername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.PaperType
     *
     * @return the value of t_exam_paper.PaperType
     *
     * @mbg.generated
     */
    public Integer getPapertype() {
        return papertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.PaperType
     *
     * @param papertype the value for t_exam_paper.PaperType
     *
     * @mbg.generated
     */
    public void setPapertype(Integer papertype) {
        this.papertype = papertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.Ratio
     *
     * @return the value of t_exam_paper.Ratio
     *
     * @mbg.generated
     */
    public String getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.Ratio
     *
     * @param ratio the value for t_exam_paper.Ratio
     *
     * @mbg.generated
     */
    public void setRatio(String ratio) {
        this.ratio = ratio == null ? null : ratio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.ExamDate
     *
     * @return the value of t_exam_paper.ExamDate
     *
     * @mbg.generated
     */
    public Date getExamdate() {
        return examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.ExamDate
     *
     * @param examdate the value for t_exam_paper.ExamDate
     *
     * @mbg.generated
     */
    public void setExamdate(Date examdate) {
        this.examdate = examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.ExamTime
     *
     * @return the value of t_exam_paper.ExamTime
     *
     * @mbg.generated
     */
    public Integer getExamtime() {
        return examtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.ExamTime
     *
     * @param examtime the value for t_exam_paper.ExamTime
     *
     * @mbg.generated
     */
    public void setExamtime(Integer examtime) {
        this.examtime = examtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.QuestionBank
     *
     * @return the value of t_exam_paper.QuestionBank
     *
     * @mbg.generated
     */
    public Integer getQuestionbank() {
        return questionbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.QuestionBank
     *
     * @param questionbank the value for t_exam_paper.QuestionBank
     *
     * @mbg.generated
     */
    public void setQuestionbank(Integer questionbank) {
        this.questionbank = questionbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.Status
     *
     * @return the value of t_exam_paper.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.Status
     *
     * @param status the value for t_exam_paper.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.Creator
     *
     * @return the value of t_exam_paper.Creator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.Creator
     *
     * @param creator the value for t_exam_paper.Creator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.CreateTime
     *
     * @return the value of t_exam_paper.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.CreateTime
     *
     * @param createtime the value for t_exam_paper.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}