package com.test.data.repository.model.domain;

import java.util.Date;

public class TExamQuestions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.Context
     *
     * @mbg.generated
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.Score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.QuestionBank
     *
     * @mbg.generated
     */
    private Integer questionbank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.QuestionType
     *
     * @mbg.generated
     */
    private Integer questiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.PaperType
     *
     * @mbg.generated
     */
    private Integer papertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.Creator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_questions.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.ID
     *
     * @return the value of t_exam_questions.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.ID
     *
     * @param id the value for t_exam_questions.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.Guid
     *
     * @return the value of t_exam_questions.Guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.Guid
     *
     * @param guid the value for t_exam_questions.Guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.Context
     *
     * @return the value of t_exam_questions.Context
     *
     * @mbg.generated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.Context
     *
     * @param context the value for t_exam_questions.Context
     *
     * @mbg.generated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.Score
     *
     * @return the value of t_exam_questions.Score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.Score
     *
     * @param score the value for t_exam_questions.Score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.QuestionBank
     *
     * @return the value of t_exam_questions.QuestionBank
     *
     * @mbg.generated
     */
    public Integer getQuestionbank() {
        return questionbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.QuestionBank
     *
     * @param questionbank the value for t_exam_questions.QuestionBank
     *
     * @mbg.generated
     */
    public void setQuestionbank(Integer questionbank) {
        this.questionbank = questionbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.QuestionType
     *
     * @return the value of t_exam_questions.QuestionType
     *
     * @mbg.generated
     */
    public Integer getQuestiontype() {
        return questiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.QuestionType
     *
     * @param questiontype the value for t_exam_questions.QuestionType
     *
     * @mbg.generated
     */
    public void setQuestiontype(Integer questiontype) {
        this.questiontype = questiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.PaperType
     *
     * @return the value of t_exam_questions.PaperType
     *
     * @mbg.generated
     */
    public Integer getPapertype() {
        return papertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.PaperType
     *
     * @param papertype the value for t_exam_questions.PaperType
     *
     * @mbg.generated
     */
    public void setPapertype(Integer papertype) {
        this.papertype = papertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.Status
     *
     * @return the value of t_exam_questions.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.Status
     *
     * @param status the value for t_exam_questions.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.Creator
     *
     * @return the value of t_exam_questions.Creator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.Creator
     *
     * @param creator the value for t_exam_questions.Creator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_questions.CreateTime
     *
     * @return the value of t_exam_questions.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_questions.CreateTime
     *
     * @param createtime the value for t_exam_questions.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}