package com.test.data.repository.model.domain;

import java.util.Date;

public class TExamRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.GuidExamPaper
     *
     * @mbg.generated
     */
    private String guidexampaper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.GuidExaminees
     *
     * @mbg.generated
     */
    private String guidexaminees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.Scores
     *
     * @mbg.generated
     */
    private Integer scores;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.Creator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.ID
     *
     * @return the value of t_exam_record.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.ID
     *
     * @param id the value for t_exam_record.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.Guid
     *
     * @return the value of t_exam_record.Guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.Guid
     *
     * @param guid the value for t_exam_record.Guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.GuidExamPaper
     *
     * @return the value of t_exam_record.GuidExamPaper
     *
     * @mbg.generated
     */
    public String getGuidexampaper() {
        return guidexampaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.GuidExamPaper
     *
     * @param guidexampaper the value for t_exam_record.GuidExamPaper
     *
     * @mbg.generated
     */
    public void setGuidexampaper(String guidexampaper) {
        this.guidexampaper = guidexampaper == null ? null : guidexampaper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.GuidExaminees
     *
     * @return the value of t_exam_record.GuidExaminees
     *
     * @mbg.generated
     */
    public String getGuidexaminees() {
        return guidexaminees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.GuidExaminees
     *
     * @param guidexaminees the value for t_exam_record.GuidExaminees
     *
     * @mbg.generated
     */
    public void setGuidexaminees(String guidexaminees) {
        this.guidexaminees = guidexaminees == null ? null : guidexaminees.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.Scores
     *
     * @return the value of t_exam_record.Scores
     *
     * @mbg.generated
     */
    public Integer getScores() {
        return scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.Scores
     *
     * @param scores the value for t_exam_record.Scores
     *
     * @mbg.generated
     */
    public void setScores(Integer scores) {
        this.scores = scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.Status
     *
     * @return the value of t_exam_record.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.Status
     *
     * @param status the value for t_exam_record.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.Creator
     *
     * @return the value of t_exam_record.Creator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.Creator
     *
     * @param creator the value for t_exam_record.Creator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.CreateTime
     *
     * @return the value of t_exam_record.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.CreateTime
     *
     * @param createtime the value for t_exam_record.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}