package com.test.data.repository.model.domain;

import java.util.Date;

public class TExamAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer.GuidExamRecord
     *
     * @mbg.generated
     */
    private String guidexamrecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer.GuidExamQuestions
     *
     * @mbg.generated
     */
    private String guidexamquestions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer.Result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer.Create_Time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer.ID
     *
     * @return the value of t_exam_answer.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer.ID
     *
     * @param id the value for t_exam_answer.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer.Guid
     *
     * @return the value of t_exam_answer.Guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer.Guid
     *
     * @param guid the value for t_exam_answer.Guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer.GuidExamRecord
     *
     * @return the value of t_exam_answer.GuidExamRecord
     *
     * @mbg.generated
     */
    public String getGuidexamrecord() {
        return guidexamrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer.GuidExamRecord
     *
     * @param guidexamrecord the value for t_exam_answer.GuidExamRecord
     *
     * @mbg.generated
     */
    public void setGuidexamrecord(String guidexamrecord) {
        this.guidexamrecord = guidexamrecord == null ? null : guidexamrecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer.GuidExamQuestions
     *
     * @return the value of t_exam_answer.GuidExamQuestions
     *
     * @mbg.generated
     */
    public String getGuidexamquestions() {
        return guidexamquestions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer.GuidExamQuestions
     *
     * @param guidexamquestions the value for t_exam_answer.GuidExamQuestions
     *
     * @mbg.generated
     */
    public void setGuidexamquestions(String guidexamquestions) {
        this.guidexamquestions = guidexamquestions == null ? null : guidexamquestions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer.Result
     *
     * @return the value of t_exam_answer.Result
     *
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer.Result
     *
     * @param result the value for t_exam_answer.Result
     *
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer.Create_Time
     *
     * @return the value of t_exam_answer.Create_Time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer.Create_Time
     *
     * @param createTime the value for t_exam_answer.Create_Time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}