package com.test.data.repository.model.domain;

import java.util.Date;

public class TExaminees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.JobNumber
     *
     * @mbg.generated
     */
    private String jobnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.Duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.Department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.Email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.Type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.QuestionBank
     *
     * @mbg.generated
     */
    private Integer questionbank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.Creator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examinees.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.ID
     *
     * @return the value of t_examinees.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.ID
     *
     * @param id the value for t_examinees.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.Guid
     *
     * @return the value of t_examinees.Guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.Guid
     *
     * @param guid the value for t_examinees.Guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.JobNumber
     *
     * @return the value of t_examinees.JobNumber
     *
     * @mbg.generated
     */
    public String getJobnumber() {
        return jobnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.JobNumber
     *
     * @param jobnumber the value for t_examinees.JobNumber
     *
     * @mbg.generated
     */
    public void setJobnumber(String jobnumber) {
        this.jobnumber = jobnumber == null ? null : jobnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.Name
     *
     * @return the value of t_examinees.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.Name
     *
     * @param name the value for t_examinees.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.Duty
     *
     * @return the value of t_examinees.Duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.Duty
     *
     * @param duty the value for t_examinees.Duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.Department
     *
     * @return the value of t_examinees.Department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.Department
     *
     * @param department the value for t_examinees.Department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.Email
     *
     * @return the value of t_examinees.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.Email
     *
     * @param email the value for t_examinees.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.Type
     *
     * @return the value of t_examinees.Type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.Type
     *
     * @param type the value for t_examinees.Type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.QuestionBank
     *
     * @return the value of t_examinees.QuestionBank
     *
     * @mbg.generated
     */
    public Integer getQuestionbank() {
        return questionbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.QuestionBank
     *
     * @param questionbank the value for t_examinees.QuestionBank
     *
     * @mbg.generated
     */
    public void setQuestionbank(Integer questionbank) {
        this.questionbank = questionbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.Status
     *
     * @return the value of t_examinees.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.Status
     *
     * @param status the value for t_examinees.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.Creator
     *
     * @return the value of t_examinees.Creator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.Creator
     *
     * @param creator the value for t_examinees.Creator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examinees.CreateTime
     *
     * @return the value of t_examinees.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examinees.CreateTime
     *
     * @param createtime the value for t_examinees.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}