package com.test.data.repository.model.domain;

import java.util.Date;

public class TPaperQuestions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper_questions.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper_questions.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper_questions.GuidExamPaper
     *
     * @mbg.generated
     */
    private String guidexampaper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper_questions.GuidExamQuestions
     *
     * @mbg.generated
     */
    private String guidexamquestions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper_questions.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper_questions.ID
     *
     * @return the value of t_paper_questions.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper_questions.ID
     *
     * @param id the value for t_paper_questions.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper_questions.Guid
     *
     * @return the value of t_paper_questions.Guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper_questions.Guid
     *
     * @param guid the value for t_paper_questions.Guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper_questions.GuidExamPaper
     *
     * @return the value of t_paper_questions.GuidExamPaper
     *
     * @mbg.generated
     */
    public String getGuidexampaper() {
        return guidexampaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper_questions.GuidExamPaper
     *
     * @param guidexampaper the value for t_paper_questions.GuidExamPaper
     *
     * @mbg.generated
     */
    public void setGuidexampaper(String guidexampaper) {
        this.guidexampaper = guidexampaper == null ? null : guidexampaper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper_questions.GuidExamQuestions
     *
     * @return the value of t_paper_questions.GuidExamQuestions
     *
     * @mbg.generated
     */
    public String getGuidexamquestions() {
        return guidexamquestions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper_questions.GuidExamQuestions
     *
     * @param guidexamquestions the value for t_paper_questions.GuidExamQuestions
     *
     * @mbg.generated
     */
    public void setGuidexamquestions(String guidexamquestions) {
        this.guidexamquestions = guidexamquestions == null ? null : guidexamquestions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper_questions.CreateTime
     *
     * @return the value of t_paper_questions.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper_questions.CreateTime
     *
     * @param createtime the value for t_paper_questions.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}