package com.test.data.repository.model.domain;

import java.util.Date;

public class TQuestionsAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questions_answer.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questions_answer.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questions_answer.GuidExamQuestions
     *
     * @mbg.generated
     */
    private String guidexamquestions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questions_answer.Context
     *
     * @mbg.generated
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questions_answer.IsRight
     *
     * @mbg.generated
     */
    private Integer isright;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questions_answer.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questions_answer.Creator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questions_answer.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questions_answer.ID
     *
     * @return the value of t_questions_answer.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questions_answer.ID
     *
     * @param id the value for t_questions_answer.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questions_answer.Guid
     *
     * @return the value of t_questions_answer.Guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questions_answer.Guid
     *
     * @param guid the value for t_questions_answer.Guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questions_answer.GuidExamQuestions
     *
     * @return the value of t_questions_answer.GuidExamQuestions
     *
     * @mbg.generated
     */
    public String getGuidexamquestions() {
        return guidexamquestions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questions_answer.GuidExamQuestions
     *
     * @param guidexamquestions the value for t_questions_answer.GuidExamQuestions
     *
     * @mbg.generated
     */
    public void setGuidexamquestions(String guidexamquestions) {
        this.guidexamquestions = guidexamquestions == null ? null : guidexamquestions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questions_answer.Context
     *
     * @return the value of t_questions_answer.Context
     *
     * @mbg.generated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questions_answer.Context
     *
     * @param context the value for t_questions_answer.Context
     *
     * @mbg.generated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questions_answer.IsRight
     *
     * @return the value of t_questions_answer.IsRight
     *
     * @mbg.generated
     */
    public Integer getIsright() {
        return isright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questions_answer.IsRight
     *
     * @param isright the value for t_questions_answer.IsRight
     *
     * @mbg.generated
     */
    public void setIsright(Integer isright) {
        this.isright = isright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questions_answer.Status
     *
     * @return the value of t_questions_answer.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questions_answer.Status
     *
     * @param status the value for t_questions_answer.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questions_answer.Creator
     *
     * @return the value of t_questions_answer.Creator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questions_answer.Creator
     *
     * @param creator the value for t_questions_answer.Creator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questions_answer.CreateTime
     *
     * @return the value of t_questions_answer.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questions_answer.CreateTime
     *
     * @param createtime the value for t_questions_answer.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}