package com.test.data.repository.model.domain;

import java.util.Date;

public class TRecordQuestions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_questions.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_questions.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_questions.GuidExamRecord
     *
     * @mbg.generated
     */
    private String guidexamrecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_questions.GuidExamQuestions
     *
     * @mbg.generated
     */
    private String guidexamquestions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_questions.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_questions.ID
     *
     * @return the value of t_record_questions.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_questions.ID
     *
     * @param id the value for t_record_questions.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_questions.Guid
     *
     * @return the value of t_record_questions.Guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_questions.Guid
     *
     * @param guid the value for t_record_questions.Guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_questions.GuidExamRecord
     *
     * @return the value of t_record_questions.GuidExamRecord
     *
     * @mbg.generated
     */
    public String getGuidexamrecord() {
        return guidexamrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_questions.GuidExamRecord
     *
     * @param guidexamrecord the value for t_record_questions.GuidExamRecord
     *
     * @mbg.generated
     */
    public void setGuidexamrecord(String guidexamrecord) {
        this.guidexamrecord = guidexamrecord == null ? null : guidexamrecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_questions.GuidExamQuestions
     *
     * @return the value of t_record_questions.GuidExamQuestions
     *
     * @mbg.generated
     */
    public String getGuidexamquestions() {
        return guidexamquestions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_questions.GuidExamQuestions
     *
     * @param guidexamquestions the value for t_record_questions.GuidExamQuestions
     *
     * @mbg.generated
     */
    public void setGuidexamquestions(String guidexamquestions) {
        this.guidexamquestions = guidexamquestions == null ? null : guidexamquestions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_questions.CreateTime
     *
     * @return the value of t_record_questions.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_questions.CreateTime
     *
     * @param createtime the value for t_record_questions.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}