package com.test.data.repository.mapper;

import com.test.data.repository.model.domain.TAnswerResult;
import com.test.data.repository.model.example.TAnswerResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAnswerResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    long countByExample(TAnswerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    int deleteByExample(TAnswerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    int insert(TAnswerResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    int insertSelective(TAnswerResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    List<TAnswerResult> selectByExample(TAnswerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    TAnswerResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAnswerResult record, @Param("example") TAnswerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAnswerResult record, @Param("example") TAnswerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAnswerResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAnswerResult record);
}