package com.test.data.repository.mapper;

import com.test.data.repository.model.domain.TExamPaper;
import com.test.data.repository.model.example.TExamPaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TExamPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    long countByExample(TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int deleteByExample(TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int insert(TExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int insertSelective(TExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    List<TExamPaper> selectByExample(TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    TExamPaper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TExamPaper record, @Param("example") TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TExamPaper record, @Param("example") TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TExamPaper record);
}