package com.test.data.repository.mapper;

import com.test.data.repository.model.domain.TExamRecord;
import com.test.data.repository.model.example.TExamRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TExamRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    long countByExample(TExamRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    int deleteByExample(TExamRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    int insert(TExamRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    int insertSelective(TExamRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    List<TExamRecord> selectByExample(TExamRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    TExamRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TExamRecord record, @Param("example") TExamRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TExamRecord record, @Param("example") TExamRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TExamRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TExamRecord record);
}