package com.test.data.repository.mapper;

import com.test.data.repository.model.domain.TExamAnswer;
import com.test.data.repository.model.example.TExamAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TExamAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    long countByExample(TExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    int deleteByExample(TExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    int insert(TExamAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    int insertSelective(TExamAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    List<TExamAnswer> selectByExample(TExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    TExamAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TExamAnswer record, @Param("example") TExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TExamAnswer record, @Param("example") TExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TExamAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TExamAnswer record);
}