package com.test.data.repository.mapper;

import com.test.data.repository.model.domain.TExamQuestions;
import com.test.data.repository.model.example.TExamQuestionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TExamQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    long countByExample(TExamQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    int deleteByExample(TExamQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    int insert(TExamQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    int insertSelective(TExamQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    List<TExamQuestions> selectByExample(TExamQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    TExamQuestions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TExamQuestions record, @Param("example") TExamQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TExamQuestions record, @Param("example") TExamQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TExamQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TExamQuestions record);
}