package com.test.data.repository.mapper;

import com.test.data.repository.model.domain.TExaminees;
import com.test.data.repository.model.example.TExamineesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TExamineesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    long countByExample(TExamineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    int deleteByExample(TExamineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    int insert(TExaminees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    int insertSelective(TExaminees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    List<TExaminees> selectByExample(TExamineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    TExaminees selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TExaminees record, @Param("example") TExamineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TExaminees record, @Param("example") TExamineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TExaminees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examinees
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TExaminees record);
}