package com.test.data.repository.mapper;

import com.test.data.repository.model.domain.TPaperQuestions;
import com.test.data.repository.model.example.TPaperQuestionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPaperQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    long countByExample(TPaperQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    int deleteByExample(TPaperQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    int insert(TPaperQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    int insertSelective(TPaperQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    List<TPaperQuestions> selectByExample(TPaperQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    TPaperQuestions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPaperQuestions record, @Param("example") TPaperQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPaperQuestions record, @Param("example") TPaperQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPaperQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPaperQuestions record);
}