package com.test.data.repository.mapper;

import com.test.data.repository.model.domain.TRecordQuestions;
import com.test.data.repository.model.example.TRecordQuestionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TRecordQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    long countByExample(TRecordQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    int deleteByExample(TRecordQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    int insert(TRecordQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    int insertSelective(TRecordQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    List<TRecordQuestions> selectByExample(TRecordQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    TRecordQuestions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TRecordQuestions record, @Param("example") TRecordQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TRecordQuestions record, @Param("example") TRecordQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TRecordQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TRecordQuestions record);
}